### PR TITLE
Update assignment_1.ipynb

### PR DESCRIPTION
**Pull request by kfuentes0524**
## Checklist
- [ ] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by amanda-ng518** [comment]
It still shows up as invalid notebook

**Comment by kfuentes0524** [comment]
I apologize for the inconvenience—I’m not sure what went wrong. I’ll create a new repository to try and resolve the issue.

**Comment by kfuentes0524** [comment]
Could you check again Please?

**Comment by amanda-ng518** [comment]
It is still showing up as invalid notebook, same thing happens with your A2

**Pull request closed without merging**
