### PR TITLE
Update assignment_1.ipynb

### PR DESCRIPTION
**Pull request by kfuentes0524**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
I implemented a KNN model for wine classification by:
Conducting a grid search to tune the n_neighbors hyperparameter using 10-fold cross-validation.
Fitting the KNN model with the best n_neighbors value found from the grid search.
## What did you learn from the changes you have made?
I learned that systematic hyperparameter tuning (like using grid search) significantly improves model performance.
## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
While implementing the KNN model, I considered using other classification algorithms (like Decision Trees or Random Forests) for comparison.
## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
One challenge I faced was ensuring that the random seed was set correctly to maintain reproducibility. I addressed this by clearly initializing the random seed before any data manipulation steps.
## Checklist
- [ ] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by amanda-ng518 — CHANGES_REQUESTED** [review]
A1: invalid notebook

**Comment by kfuentes0524** [comment]
Good morning Amanda,

Please, Could you explain me about your commet. Thanks.

**Comment by amanda-ng518** [comment]
Screenshot 2024-10-02 at 12 48 30 PM

**Comment by kfuentes0524** [comment]
Thank you Amanda.
I do not know what is the reason for that, I have create other pull request.


pull request 1

**Pull request closed without merging**
